TASK: Fix-up #4008 use GitHub ci + Speedup E2E !!! (#4022)
* WIP: Attempt to ssh into github ci?

* WIP: Fix linking of neos-ui by flushing cache

* PATCH: Ci dont override package distribution and install dont install neos ui from remote

* WIP: Still fix server run

* WIP: remove debug code

* TASK: find different way to run ts and js in testcafe

* TASK: adjust naming of tests client vs server ci confusion

* WIP naming and only run js test again???

* WIP close ssh

* WIP attempt to restore that sauce finds tests?

* WIP see if firefox 143 works

* Wip remove debug code

* Wip settle with using previous firefox version for now as latest is 144 is broken and reports no tests were run

* Wip rename files to remove ci prefix

* Wip attempt to speedup sauce test run by setting rootDir to only the fixtures

* Wip include testcafe-react-selectors from npm instead of uploading it from nodemodules

* Wip remove now obsolete sauceignore

* TASK: Ensure e2e test never log exceptions

solves https://github.com/neos/neos-ui/issues/3626

* Revert "Delete .circleci/config.yml"

This reverts commit 2dd3659c80305bb0c2b5aac61c89c6c3c4a799c8.

* PATCH: Readd circle ci file again

reverts 2dd3659c80305bb0c2b5aac61c89c6c3c4a799c8

* Revert "Wip remove now obsolete sauceignore"

This reverts commit 76cdd14cc1743497f5ffeb7bfad7c163da93614e.

* Ensure utils.js is availabe in testcafe ci

* move sauce ingore around

* copy (working) composer cache setup from neos dev collection

* PATCH: Prevent image uri implementation from throwing if `asset` is not set because image was not specified in node creation dialog

* Nmaing thbninsgf

* TASK: Use working-directory in ci to simplify job and hopefully fix composer cache

* use non deprecated registries

* close ui in correct folder

* use checkout action and working-directory also for e2e tests

* setup node and install neos ui when its mounted in Application folder

* node should find its node-version-file

* node should find its node-version-file 2

* shuffle things around and set cache-dependency-pat

* run saucectl in directory

* Fixup remove no longer needed `--disable-search-engine-choice-screen`

https://github.com/neos/neos-ui/pull/3998

* TASK: Remove complex saucelabs setup from e2e.sh file

* TASK: Remove obsolete dependency `testcafe-browser-provider-saucelabs`

saucelabs is run via sauce ctl

* Patch invoke e2e.sh correctly

* Typo

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,4 +1,4 @@
-name: Build and Test E2E
+name: E2E (Client, Server)
 on:
   workflow_dispatch:
   push:
@@ -12,12 +12,18 @@ env:
   GITHUB_TOKEN: ${{ github.token }}
 
 jobs:
-  server-build:
+  build:
+    name: "Browser Tests"
+    runs-on: ubuntu-latest
+
     env:
       FLOW_CONTEXT: Production
-      FLOW_PATH_ROOT: ../neos-base-distribution
+      DISTRIBUTION_FOLDER: neos-distribution
+      PACKAGE_FOLDER: Neos.Neos.Ui
 
-    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ${{ env.DISTRIBUTION_FOLDER }}
 
     strategy:
       fail-fast: false
@@ -43,6 +49,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          path: ${{ env.PACKAGE_FOLDER }}
 
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
@@ -50,63 +58,62 @@ jobs:
           php-version: ${{ matrix.php-version }}
           extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
+      - name: Checkout development distribution
+        uses: actions/checkout@v4
         with:
-          node-version-file: '.nvmrc'
-          cache: 'yarn'
+          repository: neos/neos-development-distribution
+          ref: ${{ matrix.neos-version }}
+          path: ${{ env.DISTRIBUTION_FOLDER }}
 
-      - id: composer-cache
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-        shell: bash
-
-      - uses: actions/cache@v3
+      - name: Cache Composer packages
+        uses: actions/cache@v4
+        timeout-minutes: 30
         with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-composer-
+          path: |
+            ~/.cache/composer
+            ${{ env.DISTRIBUTION_FOLDER }}/Packages
+          key: php-${{ matrix.php-version }}-neos-${{ matrix.neos-version }}-${{ hashFiles('**/composer.json') }}
+          restore-keys: php-${{ matrix.php-version }}-neos-${{ matrix.neos-version }}-
 
-      - name: Install npm dependencies
+      - name: Prepare Neos.Neos.Ui Package for composer installation
         run: |
-          make install
-
-      - name: Build for js for e2e
-        run: |
-          make build-e2e-testing
-
-      - name: Prepare Neos distribution
-        run: |
-          cd "../neos-ui"
+          cd "../${{ env.PACKAGE_FOLDER }}"
           # no "neos/neos-ui-compiled" because this job recompiles JS
           composer remove neos/neos-ui-compiled --no-update
           # install also export-ignore'd Test/ and packages/ directory
           rm .gitattributes
 
-          git clone --depth 1 --branch ${{ matrix.neos-version }} https://github.com/neos/neos-development-distribution.git ${FLOW_PATH_ROOT}
-          cd ${FLOW_PATH_ROOT}
+      - name: Install and link composer dependencies
+        run: |
           composer config --no-plugins allow-plugins.neos/composer-plugin true
-          composer config repositories.package '{ "type": "path", "url": "../neos-ui", "options": { "symlink": false } }'
-          composer config repositories.package '{ "type": "path", "url": "../neos-ui/Tests/IntegrationTests/TestDistribution/DistributionPackages/*", "options": { "symlink": false } }'
+          composer config repositories.package '{ "type": "path", "url": "../${{ env.PACKAGE_FOLDER }}", "options": { "symlink": false } }'
+          composer config repositories.testsites '{ "type": "path", "url": "../${{ env.PACKAGE_FOLDER }}/Tests/IntegrationTests/TestDistribution/DistributionPackages/*", "options": { "symlink": false } }'
           composer require --no-update --no-interaction neos/neos-ui:@dev
           composer require --no-update --no-interaction neos/test-onedimension:@dev
           composer require --no-update --no-interaction neos/test-twodimensions:@dev
           composer require --no-update --no-interaction neos/test-nodetypes:@dev
 
-      - name: Install Brombeer-sauce
-        run: |
-          curl -L -o sauce-connect.deb https://saucelabs.com/downloads/sauce-connect/5.3.0/sauce-connect_5.3.0.linux_amd64.deb
-          sudo dpkg -i sauce-connect.deb
-
-          npm install -g saucectl
-
-      - name: Install composer dependencies
-        run: |
-          cd ${FLOW_PATH_ROOT}
           composer install --no-interaction --no-progress --prefer-dist
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: '${{ env.DISTRIBUTION_FOLDER }}/Packages/Application/Neos.Neos.Ui/.nvmrc'
+          cache-dependency-path: '${{ env.DISTRIBUTION_FOLDER }}/Packages/Application/Neos.Neos.Ui/yarn.lock'
+          cache: 'yarn'
+
+      - name: Install npm dependencies
+        run: |
+          cd Packages/Application/Neos.Neos.Ui
+          make install
+
+      - name: Build for js for e2e
+        run: |
+          cd Packages/Application/Neos.Neos.Ui
+          make build-e2e-testing
 
       - name: Setup Flow
         run: |
-          cd ${FLOW_PATH_ROOT}
           rm -f Configuration/Settings.yaml
           cat <<EOF >> Configuration/Settings.yaml
           Neos:
@@ -123,13 +130,11 @@ jobs:
               Ui:
                 frontendDevelopmentMode: true
           EOF
+          ./flow
           ./flow doctrine:migrate
-          ./flow configuration:show --path Neos.Neos.Ui.resources
-          ./flow configuration:show --path Neos.Neos.Ui | grep frontendDevelopmentMode
 
       - name: Setup Testing Neos Sites and Users
         run: |
-          cd ${FLOW_PATH_ROOT}
           ./flow cr:setup --content-repository onedimension
           ./flow site:pruneAll --content-repository onedimension --force --verbose
           ./flow site:importAll --content-repository onedimension --package-key Neos.Test.OneDimension --verbose
@@ -145,12 +150,17 @@ jobs:
         run: |
           echo 127.0.0.1 onedimension.localhost | sudo tee -a /etc/hosts
           echo 127.0.0.1 twodimensions.localhost | sudo tee -a /etc/hosts
-          cd ${FLOW_PATH_ROOT}
           chmod 777 Web/
           ./flow resource:publish
           ./flow server:run --port 8081 &
-          sleep 1
-          curl http://onedimension.localhost:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js
+
+      - name: Setup Sauce connect and CTL
+        run: |
+          # https://docs.saucelabs.com/secure-connections/sauce-connect-5/installation/linux/
+          curl -L -o sauce-connect.deb https://saucelabs.com/downloads/sauce-connect/5.3.0/sauce-connect_5.3.0.linux_amd64.deb
+          sudo dpkg -i sauce-connect.deb
+
+          npm install -g saucectl
 
       - name: Start e2e tunnel (in background)
         run: |
@@ -158,28 +168,49 @@ jobs:
 
       - name: Run e2e tests
         run: |
-          saucectl run --config .sauce/config.yml --tunnel-name "neos-tunnel" --region "us-west-1" --artifacts.download.directory ${{ env.FLOW_PATH_ROOT }}/Data/Logs/saucelabs-artifacts
+          cd Packages/Application/Neos.Neos.Ui
+          saucectl run --config .sauce/config.yml --tunnel-name "neos-tunnel" --region "us-west-1" --artifacts.download.directory ../../../Data/Logs/saucelabs-artifacts
 
-      - name: Show testcafe output
+      - name: Show Testcafe output
         if: ${{ always() }}
         shell: bash
         run: |
-          cd ${FLOW_PATH_ROOT}
           for file in Data/Logs/saucelabs-artifacts/**/console.log; do
             echo $file
             cat $file
           done
 
-      - name: Show Flow log on failure
-        if: ${{ failure()  }}
+      - name: Assert no Flow exceptions swallowed
+        if: ${{ always() }}
         shell: bash
         run: |
-          cd ${FLOW_PATH_ROOT}
-          for file in Data/Logs/*.log; do
-            echo $file
-            cat $file
-          done
+          if [ ! -d "Data/Logs/Exceptions" ]; then
+            exit 0
+          fi
+
           for file in Data/Logs/Exceptions/*; do
             echo $file
             cat $file
+            echo "\n"
+            echo "\n"
           done
+
+          exit 1
+
+      - name: Show Flow logs on failure
+        if: ${{ failure() }}
+        shell: bash
+        run: |
+          for file in Data/Logs/*.log; do
+            echo $file
+            cat $file
+            echo "\n"
+            echo "\n"
+          done
+
+      # enable to debug container (https://upterm.dev)
+      # - name: Setup ssh session for debugging
+      #   if: ${{ failure()  }}
+      #   uses: owenthereal/action-upterm@v1
+      #   with:
+      #     wait-timeout-minutes: 5
